source 'https://rubygems.org'

gem 'github-pages', '72', group: :jekyll_plugins
gem 'jekyll-feed'
gem 'html-proofer'
gem 'jekyll-archives'
gem 'jekyll-tagging-related_posts'
group :jekyll_plugins do
  gem 'jekyll-assets', github: 'jekyll/jekyll-assets'
  gem 'jekyll-sitemap', github: 'jekyll/jekyll-sitemap'
end
